import Head from "next/head";
import { Inter } from "next/font/google";
import tw from "twin.macro";
import { ThemeToggle } from "@/lib";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App boiler template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <S>
          <ThemeToggle /> main index
        </S>
        <div tw="bg-primary border border-gray-600 dark:border-gray-100 m-2 p-2 ">
          custom tailwind primary color
        </div>
      </main>
    </>
  );
}
const S = tw.div` 
	bg-gradient-to-r
	from-violet-500 to-fuchsia-50
	rounded-sm
	p-2 m-2
	
`;
